<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <RootNamespace>Slackbot.Net.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>Preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FakeItEasy" Version="9.0.1"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0"/>
    <PackageReference Include="xunit.v3" Version="4.0.0"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Slackbot.Net.SlackClients.Http\Slackbot.Net.SlackClients.Http.csproj"/>
    <ProjectReference Include="..\..\src\Slackbot.Net.Shared\Slackbot.Net.Shared.csproj"/>
    <ProjectReference Include="..\..\src\Slackbot.Net.Endpoints\Slackbot.Net.Endpoints.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Helpers\ImageBase64Encoded.txt"/>
    <Content Include="Helpers\ImageBase64Encoded.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
