name: CI

on: [push, pull_request]
      
jobs:
  ubuntu-16_04:
    name: ubuntu-16_04
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: BuildLinux
        run: ./build.sh 
      
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: BuildWin
        run: powershell .\build.ps1
