name: CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [master]
    paths-ignore:
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore source
      - name: Build
        run: dotnet build --no-restore source
      - name: Test
        run: dotnet test --no-build source
        env:
          Slackbot_SlackApiKey_BotUser: ${{ secrets.SLACKBOT_SLACKAPIKEY_BOTUSER }}
          Slackbot_SlackApiKey_SlackApp: ${{ secrets.SLACKBOT_SLACKAPIKEY_SLACKAPP }}
