name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    uses: ./.github/workflows/publish.yml
    with:
      prerelease: false
    secrets: inherit

  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - run: git log $(git describe --tags --abbrev=0)..HEAD --oneline
      - name: Generate CHANGELOG.md
        id: releasenotes
        run: |
          gh api repos/$GITHUB_REPOSITORY/releases/generate-notes \
          -f tag_name="${{ needs.publish.outputs.version }}" \
          -q .body > CHANGELOG.md
          echo -e "\n\n" >> CHANGELOG.md
          git log $(git describe --tags --abbrev=0)..HEAD --oneline >> CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.publish.outputs.version }}
          release_name: Release ${{ needs.publish.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
